title: My LLM Learning Journey
description: A portfolio of small projects built with LLM assistance
baseurl: "/llmexercise"
theme: minima

# Image paths configuration
imagesurl: "/assets/images/projects/"
